### ISSUE TITLE
Max Loops +1

### ISSUE THREAD

**Issue by marc-gist** [Haxiboy/node-red-contrib-looptimer-advanced#2]
Max loops is not actually correct.  If set to say 8, the loop goes 9 times, 0-8 i suspect is the issue.

**Comment by Haxiboy** [comment]
From the documentation : 
"So if you set the max loops to 5, you will get 6 messages, which is 1 original message, and 5 messages from the loop."

This has the same working principle as the original node-red-contrib-looptimer.

**Comment by Jibun-no-Kage** [comment]
Original message is passed through is why this happens.  Not a problem, just how it is implemented.
