### ISSUE TITLE
cannot stop the looptimer

### ISSUE THREAD

**Issue by dddalmen** [Haxiboy/node-red-contrib-looptimer-advanced#3]
Hi,

maybe i'm doing something wrong.
I'm trying using looptimer to send over input message for a max of X times until the input value is stop.
I have two inputs:
- message 1, coming from node 1 ->triggers looptimer start and contains message to be sent over
- message 2, coming from node 2 -> used just to send msg.payload="stop"
Point is that even if i send msg.payload="stop" to looptimer, it will anyway go on looping until it reaches the max number of iteration configured.
I'm sure it's something i do wrong, but as i didn't find any detailed explanation of input/ouput, i wanted to ask.
Thanks

**Comment by Jibun-no-Kage** [comment]
I explicitly send 'STOP' (in caps), works for me, stops.

**Comment by Haxiboy** [comment]
Works with both stop and STOP.
Check attached.
 

> [
    {
        "id": "8eb4d9d.d1c3528",
        "type": "tab",
        "label": "demo",
        "disabled": false,
        "info": ""
    },
    {
        "id": "3acf3795.a4aff8",
        "type": "looptimer-advanced",
        "z": "8eb4d9d.d1c3528",
        "duration": "5",
        "units": "Second",
        "maxloops": "100",
        "maxtimeout": "1",
        "maxtimeoutunits": "Hour",
        "name": "",
        "x": 480,
        "y": 600,
        "wires": [
            [
                "ab782534.38ffd8"
            ],
            [
                "ab782534.38ffd8"
            ]
        ]
    },
    {
        "id": "ab782534.38ffd8",
        "type": "debug",
        "z": "8eb4d9d.d1c3528",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 700,
        "y": 480,
        "wires": []
    },
    {
        "id": "d6e5e6d3.320558",
        "type": "inject",
        "z": "8eb4d9d.d1c3528",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "stop",
        "payloadType": "str",
        "x": 250,
        "y": 620,
        "wires": [
            [
                "3acf3795.a4aff8"
            ]
        ]
    },
    {
        "id": "31b03ef0.71ba92",
        "type": "inject",
        "z": "8eb4d9d.d1c3528",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "STOP",
        "payloadType": "str",
        "x": 250,
        "y": 560,
        "wires": [
            [
                "3acf3795.a4aff8"
            ]
        ]
    },
    {
        "id": "96cc2144.e0013",
        "type": "inject",
        "z": "8eb4d9d.d1c3528",
        "name": "Start",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "test123",
        "payloadType": "str",
        "x": 260,
        "y": 500,
        "wires": [
            [
                "3acf3795.a4aff8"
            ]
        ]
    }
]
