### ISSUE TITLE
Is there or add message for when seconds time reached?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [Haxiboy/node-red-contrib-looptimer-advanced#4]
Is there or add message for when seconds time reached?  Max loops you send explicit message 'max loops reached' right?  So how about adding a similar message for when seconds timeout reached?  Say 'max seconds reached' in message payload?

**Comment by Haxiboy** [comment]
I will add this, and the ability to disable sending the first message when the loop starts.

**Comment by Haxiboy** [comment]
New version released, it's on NPM too. Check it out :)
