### ISSUE TITLE
TypeError: Cannot read property 'dir' of undefined

### ISSUE THREAD

**Issue by electrontube** [Haxiboy/node-red-contrib-looptimer-advanced#5]
Hello,

all examples throw the same error in version 0.0.6:

_**TypeError: Cannot read property 'dir' of undefined**_

Node-RED 3.0.2
Node 14.21.1
NPM 8.19.3

**Comment by Haxiboy** [comment]
Hello. Can you please show me where do you get this error exactly?
I've tested with the same versions as yours, and the example flow imports as intended.

I have only one example for this node.

Import -> Examples -> node-red-contrib-looptimer-advanced -> Example Flow

Node on this flow: Inject, Change, Debug, and of course the looptimer.

**Comment by electrontube** [comment]
I uninstalled and re-installed looptimer and restarted nodered, same result:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/30259931/200622330-f60b579a-a04f-4ea9-929f-92a2a945afa2.png">

**Comment by Haxiboy** [comment]
I was able to reproduce the bug. Will provide fix ASAP.

**Comment by diagonali** [comment]
> 

Hello, can confirm same error. Fix will be much appreciated. Thanks

**Comment by segator** [comment]
I confirm same error

**Comment by kuradi** [comment]
same error

**Comment by Haxiboy** [comment]
Sorry for waiting long for fix, had a lot of things to do.
I have updated loop dependency to a higher version, please update to version 0.0.7.

**Comment by kuradi** [comment]
thanx for update, but i'm still see same error

> 21 Nov 20:53:53 - [error] [looptimer-advanced:a06eae2f3043b37c] TypeError: Cannot read properties of undefined (reading 'dir')

**Comment by diagonali** [comment]
> thanx for update, but i'm still see same error
> 
> > 21 Nov 20:53:53 - [error] [looptimer-advanced:a06eae2f3043b37c] TypeError: Cannot read properties of undefined (reading 'dir')

While waiting for this to be fixed, I found out that the Trigger node built into Node Red can reproduce the functionality of Looptimer I needed to re-send a message every set number of times. You could use this until this custom node gets fixed?

**Comment by electrontube** [comment]
I can confirm, the bug is still exists in Version 0.0.7

**Comment by segator** [comment]
I confirm too

**Comment by Haxiboy** [comment]
Released: 0.0.8
Actually, the problem is with node-red when loading modules that javascript/html files are inside a subdirectory.
I've downgraded loop dependency to an older version, this should solve the problem.
Bug was not present in Windows (by a miraculous bug), but in Linux it causes this problem. Hopefully they merge the PR soon to the main version.

Please let me know if it has been solved for you too.
