### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'dir')

### ISSUE THREAD

**Issue by clundin** [Haxiboy/node-red-contrib-looptimer-advanced#6]
I have a trigger event sequence that when added the loop timer (3x with 5s delay) gives a type error? 

msg : error
"TypeError: Cannot read properties of undefined (reading 'dir')"

I'm new to node-red so it could be a user error but figured this should just work...

**Comment by Haxiboy** [comment]
See #5 i just reopened it.
